name: assassin
description: Distributed data assistant..
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1
  flutter_localized_locales: ^1.1.1
  cupertino_icons: ^0.1.3
  meta: ^1.1.8
  scoped_model: ^1.0.1
  flare_dart: ^2.3.4
  flare_flutter: ^2.0.2
  url_launcher: ^5.1.6
  vector_math: ^2.0.8
  shared_preferences: ^0.5.4
  collection: ^1.14.0
  flutter_gallery_assets: ^0.2.1
  package_info: ^0.4.0
  google_fonts: ^1.0.0
  flutter_staggered_grid_view: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test:
  path:
  args:
  grinder: ^0.8.0
  intl_translation:
  pedantic: ^1.9.0
  string_scanner: ^1.0.5

flutter:
  assets:
    - packages/flutter_gallery_assets/assets/icons/settings/settings_light.flr
    - packages/flutter_gallery_assets/assets/icons/settings/settings_dark.flr
    - packages/flutter_gallery_assets/assets/studies/starter_card.png
    - packages/flutter_gallery_assets/assets/studies/starter_card_dark.png
    - packages/flutter_gallery_assets/assets/logo/flutter_logo.png
    - packages/flutter_gallery_assets/assets/logo/flutter_logo_color.png
    - packages/flutter_gallery_assets/assets/icons/cupertino/cupertino.png
    - packages/flutter_gallery_assets/assets/icons/material/material.png
    - packages/flutter_gallery_assets/assets/icons/reference/reference.png
    - packages/flutter_gallery_assets/assets/demos/bottom_navigation_background.png
    - packages/flutter_gallery_assets/fonts/GalleryIcons.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Merriweather-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Eczar-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Montserrat-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Rubik-Bold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Merriweather-Light.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/RobotoCondensed-Bold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Raleway-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Raleway-SemiBold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/LibreFranklin-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/RobotoMono-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/LibreFranklin-ExtraBold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/LibreFranklin-Bold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Oswald-SemiBold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Oswald-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/LibreFranklin-SemiBold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Raleway-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Montserrat-Bold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Merriweather-BoldItalic.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Raleway-Light.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Rubik-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Montserrat-SemiBold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/RobotoCondensed-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/LibreFranklin-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Montserrat-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Rubik-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Eczar-SemiBold.ttf
    - packages/flutter_gallery_assets/places/india_chennai_flower_market.png
    - packages/flutter_gallery_assets/places/india_thanjavur_market.png
    - packages/flutter_gallery_assets/places/india_tanjore_bronze_works.png
    - packages/flutter_gallery_assets/places/india_tanjore_market_merchant.png
    - packages/flutter_gallery_assets/places/india_tanjore_thanjavur_temple.png
    - packages/flutter_gallery_assets/places/india_pondicherry_salt_farm.png
    - packages/flutter_gallery_assets/places/india_chennai_highway.png
    - packages/flutter_gallery_assets/places/india_chettinad_silk_maker.png
    - packages/flutter_gallery_assets/places/india_tanjore_thanjavur_temple_carvings.png
    - packages/flutter_gallery_assets/places/india_chettinad_produce.png
    - packages/flutter_gallery_assets/places/india_tanjore_market_technology.png
    - packages/flutter_gallery_assets/places/india_pondicherry_beach.png
    - packages/flutter_gallery_assets/places/india_pondicherry_fisherman.png
    - packages/flutter_gallery_assets/splash_effects/splash_effect_1.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_2.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_3.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_4.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_5.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_6.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_7.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_8.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_9.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_10.gif

  uses-material-design: true
  fonts:
    - family: GalleryIcons
      fonts:
        - asset: packages/flutter_gallery_assets/fonts/GalleryIcons.ttf
