name: assassin
description: Distributed data assistant..
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  ffi: ^0.1.3
  intl: ^0.16.1
  flutter_localized_locales: ^1.1.1
  cupertino_icons: ^0.1.3
  provider: ^4.2.0
  hive: ^1.4.1
  http: ^0.12.1
  web_socket_channel:
  qr_flutter:
  barcode_scan:
  image_picker:
  flutter_slidable:
  path_provider:
  # below need remove
  flare_dart: ^2.3.4
  flare_flutter: ^2.0.2
  url_launcher: ^5.1.6
  collection: ^1.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test:
  path:
  args:
  grinder: ^0.8.0
  intl_translation:
  pedantic: ^1.9.0
  string_scanner: ^1.0.5

flutter:
  assets:
    - assets/studies/starter_card.png
    - assets/studies/starter_card_dark.png
    - assets/studies/crane_card.png
    - assets/studies/crane_card_dark.png
    - assets/studies/fortnightly_card.png
    - assets/studies/fortnightly_card_dark.png
    - assets/studies/rally_card.png
    - assets/studies/rally_card_dark.png
    - assets/logo/flutter_logo.png
    - assets/logo/flutter_logo_color.png
    - assets/icons/cupertino/cupertino.png
    - assets/icons/material/material.png
    - assets/icons/reference/reference.png
    - assets/icons/settings/settings_light.flr
    - assets/icons/settings/settings_dark.flr

  fonts:
    - family: SourceHanSansCN
      fonts:
        - asset: assets/fonts/SourceHanSansCN-Normal.otf
  uses-material-design: true
